name: Auto-generate PR using Aider

on:
  workflow_dispatch:
    inputs:
      issue:
        required: true
        type: number
      model:
        type: choice
        required: true
        default: llama-3.3-70b-versatile
        options:
          - deepseek-r1-distill-llama-70b
          - deepseek-r1-distill-qwen-32b
          - distil-whisper-large-v3-en
          - gemma2-9b-it
          - llama-3.1-8b-instant
          - llama-3.2-1b-preview
          - llama-3.2-3b-preview
          - llama-3.2-11b-vision-preview
          - llama-3.2-90b-vision-preview
          - llama-3.3-70b-specdec
          - llama-3.3-70b-versatile
          - llama-guard-3-8b
          - llama3-8b-8192
          - llama3-70b-8192
          - mistral-saba-24b
          - qwen-2.5-32b
          - qwen-2.5-coder-32b
          - qwen-qwq-32b
          - whisper-large-v3
          - whisper-large-v3-turbo
  issues:
    types: [labeled]

env:
  model: ${{ inputs.model || llama-3.3-70b-versatile }}
  issue_number: ${{ github.event.issue.number || inputs.issue }}
  label: ${{ github.event.label.name || 'aider'  }}

jobs:
  generate:
    uses: mirrajabi/aider-github-workflows/.github/workflows/aider-issue-to-pr.yml@main
    # Check if the label is 'aider'
    if: github.event.label.name == 'aider'
    permissions:
      contents: write
      issues: read
      pull-requests: write
    with:
      issue-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.repository.default_branch }}
      model: groq/${{ inputs.model }}
    secrets: 
      groq_api_key: ${{ secrets.GROQ_API_KEY }}
